/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compuworkhr.presentacion;


import compuworkhr.controlador.DepartamentoControlador;
import compuworkhr.controlador.EmpleadoControlador;
import compuworkhr.controlador.EvaluacionControlador;
import compuworkhr.logica.EvaluacionDesempeno;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author Laura.Garcia
 */
public class EvaluacionLandingPage extends javax.swing.JFrame {
    private EvaluacionControlador evaluacionControlador;
    private DefaultTableModel modelo;
    private EmpleadoControlador empleadoControlador;
    private DepartamentoControlador departamentoControlador;
    
    
    public EvaluacionLandingPage(EvaluacionControlador evaluacionControlador) {
        this.evaluacionControlador = evaluacionControlador;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEvaluaciones = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolverHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelNombreModulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaEvaluaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Nombre Empleado", "Resultado", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEvaluaciones);
        if (tablaEvaluaciones.getColumnModel().getColumnCount() > 0) {
            tablaEvaluaciones.getColumnModel().getColumn(0).setResizable(false);
            tablaEvaluaciones.getColumnModel().getColumn(1).setResizable(false);
            tablaEvaluaciones.getColumnModel().getColumn(2).setResizable(false);
        }

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVolverHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Home.png"))); // NOI18N
        btnVolverHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVolverHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverHomeActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        labelNombreModulo1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        labelNombreModulo1.setText("Evaluación Desempeño");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(labelNombreModulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelNombreModulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnCrear)
                .addGap(47, 47, 47)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(btnVolverHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(btnVolverHome))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        CrearEvaluacionDialog dialog = new CrearEvaluacionDialog(this,true,evaluacionControlador);
        dialog.setVisible(true);
        cargarDatos();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        int filaSeleccionada = tablaEvaluaciones.getSelectedRow();
        if (filaSeleccionada >= 0) {
            EvaluacionDesempeno evaluacionSeleccionada = evaluacionControlador.getEvaluaciones().get(filaSeleccionada);
            ActualizarEvaluacionDialog dialog = new ActualizarEvaluacionDialog(this, true, evaluacionControlador, evaluacionSeleccionada);
            dialog.setVisible(true);
            cargarDatos();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una evaluación para actualizar.");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaEvaluaciones.getSelectedRow();
        if (filaSeleccionada >= 0){
            List<EvaluacionDesempeno> listaEvaluaciones = evaluacionControlador.getEvaluaciones();
            EvaluacionDesempeno evaluacionSeleccionada = listaEvaluaciones.get(filaSeleccionada);
            
            ActualizarEvaluacionDialog dialog = new ActualizarEvaluacionDialog(this, true, evaluacionControlador, evaluacionSeleccionada);
            dialog.setVisible(true);
            cargarDatos();
        } else {
            JOptionPane.showMessageDialog(this, "Por Favor, selecciona una evaluacion en la tabla para Actualizar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverHomeActionPerformed
        PaginaPrincipal menu = new PaginaPrincipal(empleadoControlador, departamentoControlador);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverHomeActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolverHome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNombreModulo1;
    private javax.swing.JTable tablaEvaluaciones;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        modelo.setRowCount(0);
        List<EvaluacionDesempeno> evaluaciones = evaluacionControlador.getEvaluaciones();
        for (EvaluacionDesempeno evaluacion : evaluaciones){
            modelo.addRow(new Object[]{
                evaluacion.getFecha(),
                evaluacion.getEmpleado(),
                evaluacion.getResultadoEvaluacion(),
                evaluacion.getComentarios()
            });
        }
    }
}
