/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compuworkhr.presentacion;

import compuworkhr.controlador.DepartamentoControlador;
import compuworkhr.controlador.EmpleadoControlador;
import compuworkhr.controlador.EvaluacionControlador;

/**
 *
 * @author Laura.Garcia
 */
public class PaginaPrincipal extends javax.swing.JFrame {
        private EmpleadoControlador empleadoCtrl;
        private DepartamentoControlador departamentoCrtl;
    
    public PaginaPrincipal(EmpleadoControlador empCtrl, DepartamentoControlador deptCtrl) {
        this.empleadoCtrl = empCtrl;
        this.departamentoCrtl = deptCtrl;
        initComponents();
        
        java.net.URL url = getClass().getResource("/imagenes/EmpleadoButton.png");
        System.out.println("URL del recurso: " + url);
        if(url != null){
            btnEmpleados.setIcon(new javax.swing.ImageIcon(url));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        lblTítulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        btnDepartamentos = new javax.swing.JButton();
        btnEvaluaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(653, 473));
        setResizable(false);

        panelHeader.setBackground(new java.awt.Color(153, 0, 153));
        panelHeader.setPreferredSize(new java.awt.Dimension(900, 100));

        lblTítulo.setBackground(new java.awt.Color(153, 153, 153));
        lblTítulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTítulo.setText("Sistema de Gestión Empleados");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(lblTítulo)
                .addGap(129, 129, 129))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTítulo)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 114));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        btnEmpleados.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EmpleadoButton.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleados.setPreferredSize(new java.awt.Dimension(114, 112));
        btnEmpleados.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmpleados);

        btnDepartamentos.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnDepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DepartamentosButton.png"))); // NOI18N
        btnDepartamentos.setText("Departamentos");
        btnDepartamentos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDepartamentos.setPreferredSize(new java.awt.Dimension(114, 112));
        btnDepartamentos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartamentosActionPerformed(evt);
            }
        });
        jPanel2.add(btnDepartamentos);

        btnEvaluaciones.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEvaluaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EvaluacionButton.png"))); // NOI18N
        btnEvaluaciones.setText("Evaluacion Desempeño");
        btnEvaluaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEvaluaciones.setPreferredSize(new java.awt.Dimension(114, 112));
        btnEvaluaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvaluacionesActionPerformed(evt);
            }
        });
        jPanel2.add(btnEvaluaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        new EmpleadoLandingPage(this.empleadoCtrl, this.departamentoCrtl).setVisible(true);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartamentosActionPerformed
        DepartamentoControlador departamentoControlador = new DepartamentoControlador();
        DepartamentoLandingPage deptPage = new DepartamentoLandingPage(departamentoControlador);
        deptPage.setVisible(true);
    }//GEN-LAST:event_btnDepartamentosActionPerformed

    private void btnEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvaluacionesActionPerformed
        EvaluacionControlador evaluacionControlador = new EvaluacionControlador();
        EvaluacionLandingPage evalPage = new EvaluacionLandingPage(evaluacionControlador);
        evalPage.setVisible(true);
    }//GEN-LAST:event_btnEvaluacionesActionPerformed


    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepartamentos;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnEvaluaciones;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTítulo;
    private javax.swing.JPanel panelHeader;
    // End of variables declaration//GEN-END:variables
}
